kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-k8s-example
spec:
  selector:
    app: spring-cloud-k8s-example
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-k8s-example
spec:
  selector:
    matchLabels:
      app: spring-cloud-k8s-example
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-k8s-example
    spec:
      containers:
        - name: spring-cloud-k8s-example
          image: spring-cloud-k8s-example
          imagePullPolicy: Never
          ports:
            - containerPort: 8080